version: "3.9"

services:
  geoscope:
    image: node:20-alpine
    working_dir: /app
    environment:
      - PORT=800
      - NODE_ENV=production
    volumes:
      - ./:/app
      - /app/node_modules
    command: sh -c "npm ci && npm start"
    ports:
      - "800:800"
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O - http://localhost:800/api/health >/dev/null 2>&1 || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 5
    restart: unless-stopped


